server:
  port: ${PORT:31001}
spring:
  application:
    name: xc-service-manage-cms
  data:
    mongodb:
      uri: mongodb://root:root@localhost:27017
      database: xc_cms
  freemarker:
    #关闭缓存，方便测试
    cache: false
    settings:
      #更新时延设置为0，立即更新
      template_update_delay: 0
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    virtualHost: /
eureka:
  client:
    #服务注册开关
    registerWithEureka: true
    #服务发现开关
    fetchRegistry: true
    #Eureka客户端与Eureka服务端进行交互的地址，多个中间用逗号分隔
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:50101/eureka/,http://localhost:50102/eureka/}
  instance:
    #将自己的ip地址注册到Eureka服务中
    prefer-ip-address: true
    ip-address: ${IP_ADDRESS:127.0.0.1}
    #指定实例id
    instance-id: ${spring.application.name}:${server.port}